@startuml image-processing-pipeline
skinparam defaultTextAlignment center
skinparam dpi 270
skinparam nodesep 50

' left to right direction

rectangle "RGB2GRAY" as GRAY
rectangle "Размытие \nпо Гауссу" as GAUSS
rectangle "Пороговая \nфильтрация \n(бинаризация)" as THRESHOLD

Camera -> GRAY: "bgr\nframe"
GRAY -> GAUSS: "gray\nframe"
GAUSS -> THRESHOLD
THRESHOLD -> bin_frame

@enduml